replay-framework/replay

- framework/src/play/mvc/Scope.java
- framework/test/play/mvc/ScopeTest.java
story in pivotal https://www.pivotaltracker.com/story/show/156334928
should be merged after IB branch goes live
> Fix params contains

- README.md
> Improve the porting guide

- CHANGELOG.md
- CONTRIBUTING.md
- build.gradle
- framework/src/play/data/validation/ValidationPlugin.java
It seems the problem was introduces after upgrading oval dependency from 1.84 to much newer 3.2.0
> #36 fix annotation-based validation

- README.md
It was wrong, updated the README to reflect how it actually works.
> Improve README on topic of hot-swapping

- replay-tests/helloworld/app/controllers/HelloWorld.java
- replay-tests/helloworld/app/hello/plugins/PdfGeneratorSamplePlugin.java
- replay-tests/helloworld/app/hello/plugins/PlainTextTemplate.java
- replay-tests/helloworld/app/views/hello.txt
- replay-tests/helloworld/conf/play.plugins
- replay-tests/helloworld/conf/routes
- replay-tests/helloworld/test/ui/hello/HelloPdfWorldSpec.java
One possible solution for https://github.com/codeborne/replay/issues/53
> add an example how to implement custom plugin for generating HTML for PDF

- framework/build.gradle
These are the last deps that I think can be safely removed.
> Remove not-strictly-RePlay dependencies

- framework/src/play/data/validation/Error.java
- framework/src/play/data/validation/Validation.java
...while respecting the immutability of Error
Closes #75 
Closes #74
> Bring back removed functionality

- framework/src/play/plugins/PluginDescriptor.java
Signed-off-by: cies <cies-AT@stager-DOT.nl>
Closes #77
> Expose the constuctor

- framework/src/play/mvc/Router.java
Signed-off-by: cies <cies-AT@stager-DOT.nl>
Closes #78
> Allow null Play.routes in Router.detectChanges()

- .github/dependabot.yml
- .github/release-drafter.yml
- .github/workflows/test.yml
- replay-tests/helloworld-kotlin/app/public/hello_world.txt
- replay-tests/helloworld-kotlin/conf/routes
- replay-tests/helloworld-kotlin/test/ui/hello/kotlin/HelloWorldSpec.kt
now we run the build only for master branch, and for all pull requests.
> avoid running build twice for every branch

- framework/src/play/Play.java
Signed-off-by: cies <cies-AT@stager-DOT.nl>
Closes #76
> Expose beanSource and make static

- .github/workflows/test.yml
- .run/criminals.run.xml
- README.md
it was moved to RePlay project integration tests
> update links to "criminals" app

- .github/workflows/test.yml
- CONTRIBUTING.md
- replay-tests/replay-tests.gradle
it will allow us to disable some tests only for Netty4.
> declare separate gradle tasks for tests on Netty3 and Netty4

- replay-tests/criminals/test/ui/BaseUITest.java
- replay-tests/helloworld-kotlin/test/ui/hello/kotlin/BaseSpec.kt
- replay-tests/helloworld/test/ui/hello/BaseSpec.java
- replay-tests/liquibase-app/test/ui/petstore/BaseSpec.java
- replay-tests/replay-tests.gradle
Selenium allows using Java11 built-in http client instead of Netty.
> avoid using Netty in UI tests

- netty3/src/play/server/netty3/PlayHandler.java
- netty3/test/play/server/netty3/PlayHandlerTest.java
We get large error+warn log blocks when URI parsing fails. And somehow is fails quite a bit lately (doe to a new feature where our clients are making up query params).
Currently a URI parse error results in a 500. Which I think should be a 400 (and Play2 agrees here it seems https://github.com/playframework/playframework/issues/10072 ).
I've considered Play2's approach of using the IllegalArgumentException to trigger a 400, but this STILL results in a printed stack trace, which I believe is overkill for a URI parse error.
So I've kept the URISyntaxException and given it a special treatment of only writing a singe INFO line. The Play2 discussion said a warning is not appropriate here, which I think it fair.
Two tests are added.
> Less logging and 400 response on URI parsing error

- framework/test/play/data/parsing/TextParserTest.java
- netty3/test/play/server/netty3/FileChannelBufferTest.java
- netty3/test/play/server/netty3/ResettableFileInputStreamTest.java
- pdf/src/org/allcolor/yahp/cl/converter/CHtmlToPdfFlyingSaucerTransformer.java
> Use Files instead of File

- README.md
- framework/src/play/modules/logger/RePlayLogoPlugin.java
- replay-tests/criminals/conf/play.plugins
Put `0:play.modules.logger.RePlayLogoPlugin` in your `play.plugins` and let the magic happen!
To use your own logo just check the sources for hint and create your own LogoPlugin!
> The most important thing: A cool logo

- framework/build.gradle
- framework/src/play/db/Configuration.java
- framework/src/play/db/Model.java
- framework/src/play/db/jpa/GenericModel.java
- framework/src/play/db/jpa/JPA.java
- framework/src/play/db/jpa/JPABase.java
- framework/src/play/db/jpa/JPAModelLoader.java
- framework/src/play/db/jpa/JPAPlugin.java
- framework/src/play/db/jpa/JPARepository.java
- framework/src/play/db/jpa/JPQL.java
- framework/src/play/db/jpa/Model.java
- framework/src/play/db/jpa/PersistenceUnitInfoImpl.java
- framework/test/play/db/ConfigurationTest.java
- replay-tests/liquibase-app/app/model/Pet.java
- replay-tests/liquibase-app/app/model/PetRepository.java
> Migrate javax.persistence -> jakarta.persistence

- .gitignore
- .idea/.gitignore
My dev env keeps suggesting to commit files excluded with this wildcard path.
> Selectively .gitignore files in `.idea/`

- framework/src/play/db/jpa/JPABase.java
I back-ported these changes from Play1 framework to RePlay: https://github.com/playframework/play1/pull/1431/files
> #230 remove initialization of unused variable

- framework/src/play/mvc/Http.java
- framework/src/play/mvc/Router.java
- framework/src/play/mvc/results/Redirect.java
- framework/test/play/PlayBuilder.java
- framework/test/play/data/binding/BeanWrapperTest.java
- framework/test/play/data/binding/BinderTest.java
- framework/test/play/data/binding/types/CalendarBinderTest.java
- framework/test/play/data/binding/types/DateBinderTest.java
- framework/test/play/data/binding/types/LocalDateBinderTest.java
- framework/test/play/data/binding/types/LocalDateTimeBinderTest.java
- framework/test/play/data/binding/types/LocalTimeBinderTest.java
- framework/test/play/i18n/LangTest.java
- framework/test/play/modules/logger/RequestLogPluginTest.java
- framework/test/play/mvc/HttpRequestTest.java
- framework/test/play/mvc/RouterTest.java
- javanet/src/play/server/javanet/PlayHandler.java
- javanet/test/play/server/javanet/PlayHandlerTest.java
- netty3/src/play/server/netty3/PlayHandler.java
- netty3/test/play/server/netty3/PlayHandlerTest.java
- netty4/src/play/server/netty4/PlayHandler.java
- netty4/test/play/server/netty4/PlayHandlerTest.java
- pdf/src/play/modules/pdf/PdfResult.java
> Provide method isSecure() (with caching), remove property secure

- fastergt/src/play/modules/gtengineplugin/gt_integration/GTGroovyBase1xImpl.java
- framework/src/play/mvc/Http.java
- framework/src/play/mvc/Router.java
- framework/src/play/templates/ExecutableTemplate.java
- framework/test/play/mvc/RouterTest.java
> Add more specific url builder overloads

- framework/src/play/libs/Signer.java
- framework/src/play/mvc/FlashStore.java
- framework/src/play/mvc/ForbiddenException.java
- framework/src/play/mvc/SessionDataEncoder.java
- framework/test/play/libs/SignerTest.java
- framework/test/play/mvc/FlashStoreTest.java
+ cleanups + add tests
Fixes #275
> Reduce exception throwing from FlashStore

- framework/src/play/db/jpa/Model.java
> Make Model.id field protected, improving getter/setter

- javanet/src/play/server/javanet/PlayHandler.java
- netty3/src/play/server/netty3/PlayHandler.java
- netty4/src/play/server/netty4/PlayHandler.java
> Log exception class name when 500 occures

- framework/build.gradle
- framework/src/play/Play.java
- framework/src/play/db/jpa/JPARepository.java
- framework/src/play/libs/ws/WSAsync.java
- framework/src/play/mvc/ActionInvoker.java
- framework/src/play/mvc/FlashStore.java
- framework/src/play/mvc/Redirector.java
- netty3/src/play/server/netty3/HttpServerPipelineFactory.java
- netty4/src/play/server/netty4/HttpServerInitializer.java
- pdf/src/play/modules/pdf/PdfGenerator.java
- replay-tests/criminals/app/controllers/Criminals.java
- replay-tests/criminals/app/controllers/Login.java
- replay-tests/criminals/app/services/CriminalSafetyCalculator.java
- replay-tests/criminals/app/services/OtpCodeService.java
- replay-tests/criminals/app/services/RestClient.java
- replay-tests/criminals/test/ui/MailServerEmulator.java
- replay-tests/dependency-injection/app/jobs/CounterUpdaterJob.java
- replay-tests/dependency-injection/app/jobs/CounterUpdaterJob2.java
- replay-tests/dependency-injection/app/jobs/CounterUpdaterJob3.java
- replay-tests/dependency-injection/app/plugins/DebugPlugin.java
- replay-tests/dependency-injection/app/services/Counter.java
- replay-tests/dependency-injection/app/services/Mathematics.java
- replay-tests/liquibase-app/app/controllers/PetApi.java
- replay-tests/liquibase-app/app/controllers/PetRegistration.java
- replay-tests/liquibase-app/app/controllers/PetReport.java
- replay-tests/liquibase-app/app/controllers/PetStore.java
- replay-tests/liquibase-app/app/model/PetRepository.java
> Replace javax.inject with jakarta.inject

- README.md
- framework/src/play/data/validation/UniqueCheck.java
- framework/src/play/db/jpa/GenericModel.java
- framework/src/play/db/jpa/JPABase.java
- replay-tests/liquibase-app/app/model/IdModel.java
- replay-tests/liquibase-app/app/model/Pet.java
> Deprecate jpa.Model
