- framework/build.gradle
- framework/src/play/mvc/Scope.java
- framework/test/play/mvc/CookieSessionStoreTest.java
- framework/test/play/mvc/SessionTest.java
- guice/build.gradle
Preserve timestamp in session.clear() as otherwise new session will be created in CookieSessionStore.restore() and all the data added after clearing session will be lost.
In addition, upgrade guice to 4.2.0, which already has full java9 support.
> Preserve timestamp in session.clear() + upgrade guice

- CHANGELOG.md
- build.gradle
- framework/src/play/data/parsing/TextParser.java
- framework/src/play/server/FileChannelBuffer.java
- framework/src/play/server/ResettableFileInputStream.java
- framework/test/play/data/parsing/TextParserTest.java
- framework/test/play/server/ResettableFileInputStreamTest.java
fix for https://github.com/codeborne/replay/issues/41
> fix "IOException: mark/reset not supported" when parsing http params

- fastergt/build.gradle
- framework/build.gradle
- pdf/build.gradle
I want to force our code base to only use `commons-lang3`, but RePlay exposes it.
I do not think it is required to be exposed, so I took a stab at hiding it in RePlay.
> Do not expose Apache's commons-lang v2

- framework/build.gradle
All tests still run. I did not see the dependency used anywhere in the code (no `import` from the package).
Did no see any usage in Play1 either (weird?) -- maybe this is used only at runtime, or from Groovy?
For some nice 90s vibes have a look at the webpage:
https://ezmorph.sourceforge.net/dependencies.html
It seems ezmorph is not maintained since 2008.
> Remove ezmorph dependency

- framework/build.gradle
I found some more dependencies that seemed to be unused in RePlay itself and in our code base as well. See the changes to know what.
All tests still run green.
Sure this may break code of projects using RePlay, but they can easily add the library to their own dependency specification (which I consider the correct thing to do in this case: why should a framework dictate the choice?).
> Remove more dependencies

- framework/build.gradle
Removed it and all tests still run green.
It seems to be a package that was used before the `javax.cache:cache-api` is part of Java's std lib.
Last change to this project was in January 2009.
More info:
* https://sourceforge.net/projects/jsr107cache/
* https://github.com/jsr107/jsr107spec
It seems this package was needed by EHCache, which currently depends on `javax.cache:cache-api:1.1.0`.
> Remove jsr107cache dependency

- framework/src/play/Play.java
- framework/src/play/mvc/Router.java
- framework/src/play/plugins/PluginCollection.java
- framework/test/play/plugins/PluginCollectionTest.java
Allow a minimal way to init RePlay:
* no modules (we dont use them)
* no routes from routes file: we use the `resetForTest()` method nowadays to set our test defs based on a Kotlin file
* no plugins from `.plugins` file: we want to set them from code
* no loading of config file `config/application.conf` (we stopped using it and use configure our app from code)
Additional changes:
* rename  `resetForTest()` to `setRoutes(...)`  as we use it to load our in-Kotlin-code route definitions (and the tests do not seem to use it at all)
* rename `setRoutes()` to `loadRoutesFromFile()` to articulate the difference with `setRoutes(...)` (which it calls)
* re-use the renamed `setRoutes(...)` method by the `loadRoutesFromFile()` (no parameters) method to better signal intent
* rename internal …
> Make RePlay more modular

- framework/src/play/plugins/PluginCollection.java
- framework/src/play/plugins/PluginDescriptor.java
Missed that the PluginDescriptor should be part of the erxposed API.
> Expose plugin descriptor

- framework/src/play/data/validation/Error.java
- framework/src/play/data/validation/ValidCheck.java
- framework/src/play/data/validation/Validation.java
- framework/src/play/data/validation/ValidationPlugin.java
- framework/src/play/libs/Crypter.java
- framework/src/play/server/PlayHandler.java
- framework/src/play/utils/ErrorsCookieCrypter.java
- framework/test/play/data/validation/ErrorTest.java
- framework/test/play/data/validation/ValidationPluginTest.java
- framework/test/play/data/validation/ValidationTest.java
- framework/test/play/utils/ErrorsCookieCrypterTest.java
I found some old branch. Decided to submit a pull request - seems to be useful change.
> Encrypt error cookie

- framework/src/play/server/netty3/FileService.java
- framework/src/play/server/netty4/FileService.java
- framework/src/play/server/netty4/PlayHandler.java
Until this change, we ignored the fact that Future might be failed, and just logged "serving succeeded" message.
Thus we didn't see this error after upgrade to Netty4:
```
ERROR ~ failed to serve /Users/andrei/projects/replay/replay-tests/helloworld/app/public/hello_world.txt in 6.154 ms
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: PooledUnsafeHeapByteBuf, state: 0
at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:108)
at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContex …
```
> fix serving static resources

- replay-tests/criminals/test/ui/BaseUITest.java
Commit 858f2da5ba27 removed the hardwired dependency to Chrome browser (#67).
Later the "criminals" app was imported to help integration tests, reintroducing the hardwired dependency.
Fixes: 2bf34606a1c5
> make UI tests params configurable in "criminals" app too (see #67)

- CHANGELOG.md
- framework/build.gradle
- guice/build.gradle
This allows to start migration from javax to jakarta namespace.
see https://github.com/google/guice/wiki/Guice600
> bump Guice from 5.1.0 to 6.0.0

- framework/src/play/server/Server.java
It is no "javanet:" between "replay:" and "netty3": `com.codeborne.replay:netty3`
Fixes: 02596f83a98 ("Make the error message more actionable")
> Typo was made around netty3 dependency in play.server.Server.start()

- framework/src/play/data/binding/Binder.java
We got the following error:
```
by: java.lang.NullPointerException: Cannot invoke "play.data.binding.BeanWrapper.getWrappers()" because "bw" is null
at play.data.binding.Binder.internalBindBean(Binder.java:325)
at play.data.binding.Binder.bindBean(Binder.java:319)
at play.db.jpa.GenericModel.edit(GenericModel.java:206)
```
It seems that `BeanWrapper bw = getBeanWrapper(bean.getClass());` (Binder.java:324) can return null. I'm not sure why. Maybe because our bean (Entity) did not have a default constructor: that's my hunch for now.
Since it breaks down the line with a null BeanWrapper, I think it is better to fail early and provide some hint as to what class does not have a bean wrapper.
> Drop a hint on why there is no BeanWrapper

- framework/src/play/PlayLoggingSetup.java
- framework/test/conf/log4j.properties
- framework/test/play/PlayLoggingSetupTest.java
Hi @asolntsev ,
this is another low hanging fruit: let the Framework load the `log4j.properties` from `conf` directory if exists.
I also added a failing test before implementing the improvement.
> Load `conf/log4j.properties` automatically if exists

- framework/src/play/mvc/ActionInvoker.java
- framework/src/play/mvc/Controller.java
- framework/src/play/mvc/PlayContextController.java
- framework/src/play/mvc/PlayController.java
We currently inherit from `Controller`. I want to remove some of it's capabilities in some cases (say in case of controllers that are only concerned with API requests). And I want to add some capabilities in other cases.
So I added the PlayContextController interface in between Controller and PlayController which defines the setContext() method, so ActionInvoker will be able to add the context to the controller I implement.
> Make "play.mvc.Controller".setContext implementable

- framework/build.gradle
Found that hibernate 5.6 only supports persistence-api version 3.0.0
As explained here:
https://hibernate.org/orm/releases/
> Lower `persistence-api` version in line with Hibernate's requirement

- framework/src/play/inject/Injector.java
This is used internally and in our code and works better (actually works) than the replacement that is suggested.
> Remove deprecation from Injector.getBeanOfType

- framework/src/play/modules/logger/RePlayLogoPlugin.java
Plugin "Replay logo" tries to read file "play/version" from classpath. But this file is not available when we develop & run Replay app in IDE.
> don't fail app start in development mode

- .github/dependabot.yml
- fastergt/build.gradle
Replay still supports Java 11 but ECJ dropped that in version 3.34.0.
See https://github.com/eclipse-jdt/eclipse.jdt.core/commit/c25e22b15eebcc780b1a6c54d7af1911841c49b8
See previous dependabot attempts: #187, #247, #298
> Prevent ecj (used by fastergt plugin) updates for 3.34.0 and higher

- .github/dependabot.yml
The ECJ 3.34.0+ PR (#299) wasn't tested and of course it didn't work:
> The property '#/updates/0/ignore/3/versions' includes invalid version requirements for a gradle ignore condition
This is tested now, and also allows to lift the version. Got a hint from a SO question: [How can I change my dependabot config to exclude major versions](1).
[1]: https://stackoverflow.com/a/64042332
Fixes: f074b28e2af2 ("Prevent ecj (used by fastergt plugin) updates for 3.34.0 and higher")
> Fix dependabot ignore settings for ecj

- build.gradle
- replay-tests/helloworld-kotlin/build.gradle
to avoid build time errors:
```
> Task :framework:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong: Execution failed for task ':framework:compileJava'.
> invalid source release: 11
```
Since Gradle 8.0.2 one needs to opt in for automatic toolchain provisioning with adding plugins to "settings.gradle".
See [Gradle: Toolchains for JVM projects](https://docs.gradle.org/8.5/userguide/toolchains.html) for details!
The best way to target a Java version is to build with that specific version of Java.
If that's not possible, one could use the "release" option, available from Java 10 within Gradle.
See [Gradle: Targeting a specific Java version](https://docs.gradle.org/8.5/userguide/building_java_projects.html#sec:java_cross_compilation) for details.
While at it, let …
> gradle: explicitly require specific version of Java toolchain

- framework/src/play/modules/logger/RequestLogPlugin.java
- framework/test/play/modules/logger/RequestLogPluginTest.java
The issue was caused by accidentally importing `java.lang.Error` instead of `play.mvc.results.Error` :)
```java
java.lang.ClassCastException: class java.lang.Error cannot be cast to class play.mvc.results.Result (java.lang.Error is in module java.base of loader 'bootstrap'; play.mvc.results.Result is in unnamed module of loader 'app')
at play.modules.logger.RequestLogPlugin.onActionInvocationFinally(RequestLogPlugin.java:107)
```
> fix ClassCastException in RequestLogPlugin

- framework/src/play/data/binding/ParamNode.java
- framework/test/play/data/binding/BinderTest.java
> Improve performance, add test, small cleanups

- framework/src/play/plugins/PluginCollection.java
- framework/test/play/plugins/PluginCollectionTest.java
> Make method `PluginCollection.loadPlugins(SortedSet)` public again

- javanet/src/play/server/javanet/Server.java
We already listened "0.0.0.0" in "netty3" and "netty4" implementations, but not in "javanet".
> #395 listen incoming requests on address "0.0.0.0" instead of "localhost"

- build.gradle
- excel/build.gradle
- fastergt/build.gradle
- framework/build.gradle
- gradle/libs.versions.toml
- javanet/build.gradle
- liquibase/build.gradle
- netty3/build.gradle
- netty4/build.gradle
- pdf/build.gradle
- replay-tests/criminals/build.gradle
- replay-tests/helloworld-kotlin/build.gradle
- replay-tests/helloworld/build.gradle
- replay-tests/liquibase-app/build.gradle
- replay-tests/multi-module-app/app/build.gradle
- replay-tests/replay-tests.gradle
It works really well for us. All the dep specs in one place. Is understood by Dependabot and IntelliJ (unlike the $xyzVersion interpolation we were using). Ties in really nice with the KTS syntax/tooling (autocompletion, etc.)
> Extract dependency specs to TOML catalog

- framework/src/tags/script.tag
- framework/src/tags/stylesheet.tag
- replay-tests/helloworld/app/controllers/HelloWorld.java
- replay-tests/helloworld/app/views/HelloWorld/empty.html
- replay-tests/helloworld/conf/routes
- replay-tests/helloworld/test/ui/hello/TagsInvolvesStaticFilesSpec.java
- replay-tests/replay-tests.gradle
["tags/script.tag"](https://github.com/replay-framework/replay/blob/085b20ba214cfece56d5be97dd3be7af0321d0bf/framework/src/tags/script.tag) and ["tags/stylesheet.tag"](https://github.com/replay-framework/replay/blob/085b20ba214cfece56d5be97dd3be7af0321d0bf/framework/src/tags/stylesheet.tag) files were left out from
the rename commit 397f4cac915af7be84753d009b6bcc84cb3c0d5e.
Fixes: 397f4cac915a ("rename 'getVirtualFile()' to just 'file()'")
> framework: fix leftover Play.getVirtualFile() usage in tags (#198, #291) 

- framework/build.gradle
Not sure what went wrong, but the dependencies in `framework` that should have been removed were still there.
This removes then and reorgs the list a little.
> Actually remove deps

- framework/src/play/mvc/Scope.java
We had them defined locally, which it weird: they should come from the source.
> Expose flash keys ERROR and SUCCESS

- fastergt/src/play/modules/gtengineplugin/gt_integration/GTJavaBase1xImpl.java
- fastergt/src/play/modules/gtengineplugin/gt_integration/GTPreCompiler1xImpl.java
- fastergt/src/play/templates/ExecutableTemplate.java
Remove `play.templates.ExecutableTemplates#__reverseWithCheck*()` methods as the only consumer
(`play.templates.GroovyTemplateCompiler#action()`) was gone with this `play.templates.ExecutableTemplates` class' debut in commit 185ca449d2d1cf656f3aed973625b4a0f0bea3f8.
**asolntsev**'s guess is that most of code in `ExecutableTemplates` is not used anymore.
It was used in "default" groovy templates in Play1 which were replaced by "faster groovy templates" in Replay.
But leave that cleanup for later!
While at it, improve their counterpart in fastergt plugin (`GTJavaBase1xImpl` and `GTPreCompiler1xImpl` classes and PR #524), to use the other two methods: `__reverseWithCheck_absolute_true()` and `__reverseWithCheck_absolute_false()`.
Ref: …
> fastergt: remove `__reverseWithCheck*` methods from `ExecutableTemplates`

- framework/src/play/templates/TemplateLoader.java
- javanet/src/play/server/javanet/PlayHandler.java
- replay-tests/helloworld/app/views/hello.html
- replay-tests/helloworld/build.gradle
- replay-tests/helloworld/test/ui/hello/LinksInHtmlSpec.java
- replay-tests/replay-tests.gradle
When handling `@{'...'}`, method `Router.__reverseWithCheck()` is used.
@xabolcs
> add test showing how to use `@{...}` and `@{'...'}` in html templates

- CHANGELOG.md
- framework/src/play/ConfLoader.java
- framework/src/play/ConfProperties.java
- framework/src/play/Play.java
- framework/src/play/PropertiesConfLoader.java
- framework/src/play/libs/Mail.java
- framework/src/play/libs/ws/WSAsync.java
- framework/src/play/mvc/Http.java
- framework/src/play/mvc/Router.java
- framework/src/play/mvc/Scope.java
- framework/src/play/mvc/results/NotModified.java
- framework/src/play/server/ServerHelper.java
- framework/src/play/utils/OrderSafeProperties.java
- framework/test/play/PlayBuilder.java
- framework/test/play/PlayLoggingSetupTest.java
- framework/test/play/data/validation/ValidationTest.java
- framework/test/play/db/ConfigurationTest.java
- framework/test/play/mvc/RouterTest.java
- javanet/src/play/server/javanet/PlayHandler.java
- netty3/src/play/server/netty3/PlayHandler.java
- netty4/src/play/server/netty4/PlayHandler.java
- pdf/src/play/modules/pdf/ReplayUserAgent.java
We were doing the same thing in many places.
I added a helper method. I can also think of another way to implement this: subclass `Properties` to `PlayProperties` and add the helper method there.
@xabolcs Sorry for adding some IntelliJ spelling fixes into this PR. I'm very much in the habit of scanning every file I touch for minor cleanup work.
> Add helper to Properties class +cleanups

- build.gradle
otherwise, dependabot suggests to update multiple dependencies to strange versions like "3.10.6.Final-redhat-00001".
See for example https://github.com/replay-framework/replay/pull/562#issuecomment-2794621035
> use RedHat repository only for the needed dependency
